### ISSUE TITLE
Implement message board skeleton per first ChatGPT query

### ISSUE THREAD

**Issue by ciminibb** [ciminibb/networks-project-2#2]
See the following https://chat.openai.com/share/0fd312f4-336b-4e7d-b4bc-41bfd337f581

**Comment by ciminibb** [comment]
This is cool. Only issue I can see so far is that clients can't see messages from other clients. Might be something that comes in later features

**Comment by stetsonk** [comment]
I don't know why I didn't think about that. I thought since the server was seeing them everything was good. I'll try and implement that tonight
