### ISSUE TITLE
Add public group feature

### ISSUE THREAD

**Issue by ciminibb** [ciminibb/networks-project-2#4]
Include the following features.
- All users belong to one public group.
- The server keeps track of all users that join or leave the group.
- When a user joins or leaves the group, all others get notified.
- When a user joins the group, they can see only two previous messages.
- A list of members is displayed to new users.

**Comment by BlairBowen** [comment]
@ciminibb is there anything that actually has to be changed for this? I think the current implementation is already one public group.

**Comment by ciminibb** [comment]
Yeah I think so too, I'll close the issue
